version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Aditya
      MYSQL_DATABASE: crud_app
    volumes:
      - mysql-data:/var/lib/mysql
      # Remove this line if you don't have mysql-init folder
      # - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    image: prathyusha687/backend:latest  # Changed from build: ./api
    container_name: backend-api
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Aditya
      DB_NAME: crud_app
      JWT_SECRET: devopsShackSuperSecretKey
      RESET_ADMIN_PASS: 'true'
    depends_on:
      - mysql
    ports:
      - "5000:5000"

  frontend:
    image: prathyusha687/frontend:latest  # Changed from build: ./client
    container_name: frontend-react
    restart: unless-stopped
    ports:
      - "80:80"  # Changed from 3000:80 to 80:80
    depends_on:
      - backend

volumes:
  mysql-data: