name: DevSecOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-and-quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for SonarQube analysis
    
    - name: Setup Node.js 23
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'npm'
    
    - name: Frontend Compilation Check
      run: |
        cd client
        find . -name "*.js" -exec node --check {} +
    
    - name: Backend Compilation Check
      run: |
        cd api
        find . -name "*.js" -exec node --check {} +
    
    - name: Install GitLeaks
      run: |
        wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
        tar -xzf gitleaks_8.18.0_linux_x64.tar.gz
        sudo mv gitleaks /usr/local/bin/
        chmod +x /usr/local/bin/gitleaks
    
    - name: GitLeaks Scan - Frontend
      run: |
        gitleaks detect --source ./client --exit-code 1 || echo "GitLeaks found issues in frontend"
    
    - name: GitLeaks Scan - Backend
      run: |
        gitleaks detect --source ./api --exit-code 1 || echo "GitLeaks found issues in backend"
    
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectName=DevSecoOps-project
          -Dsonar.projectKey=Pratyushaa94_DevSecoOps-project
          -Dsonar.organization=pratyushaa94
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io
    
    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
    
    - name: Trivy Filesystem Scan
      run: |
        trivy fs --format table -o fs-report.html .
        trivy fs --format sarif -o trivy-results.sarif .
    
    - name: Upload Trivy Scan Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: trivy-fs-report
        path: fs-report.html
    
    - name: Upload Security Scan Results to GitHub Security Tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: trivy-results.sarif
      continue-on-error: true